### PR TITLE
Handle Jasmine 3.3

### LINKED ISSUE #221: Deprecation warning with Jasmine-Core@3.3.0
[Jasmine-Core 3.3.0 release nodes](https://github.com/jasmine/jasmine/blob/master/release_notes/3.3.0.md)

> Introduce a configuration object to Env deprecating old single use functions

The test fails as well, however I am not sure if that is something that could be fixed here.

```text
HeadlessChrome 0.0.0 (Mac OS X 10.13.6) ERROR: 'DEPRECATION:', 'Setting specFilter directly on Env is deprecated, please use the specFilter option in `configure`'
HeadlessChrome 0.0.0 (Mac OS X 10.13.6) ERROR
  {
    "message": "TypeError: this.deprecated is not a function\n    at Env.throwOnExpectationFailure (/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1079:12)\n    at setOption (/node_modules/karma-jasmine/lib/adapter.js:354:7)\n    at ContextKarma.start (/node_modules/karma-jasmine/lib/adapter.js:343:5)\n    at ContextKarma.loaded (http://localhost:9876/context.js:168:14)\n    at http://localhost:9876/context.html:47:22",
    "str": "TypeError: this.deprecated is not a function\n    at Env.throwOnExpectationFailure (/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1079:12)\n    at setOption (/node_modules/karma-jasmine/lib/adapter.js:354:7)\n    at ContextKarma.start (/node_modules/karma-jasmine/lib/adapter.js:343:5)\n    at ContextKarma.loaded (http://localhost:9876/context.js:168:14)\n    at http://localhost:9876/context.html:47:22"
  }
HeadlessChrome 0.0.0 (Mac OS X 10.13.6): Executed 0 of 0 ERROR (0.122 secs / 0 secs)
```

### PR DESCRIPTION
**Pull request by Lalem001**
Manually tested, and confirmed to work with Jasmine@3.0.0 and Jasmine@3.3.0.

Resolves #221

Needs:
- A way to automate testing in the different versions of Jasmine

### CODE REVIEW

**Comment by nasvillanueva** [comment]
Is it an option to use yarn to install multiple versions of jasmine-core? We can have a modified `lib/index.js` for jasmine-core@3.3.0 tests that would `require.resolve` version 3.3.0.

Something like 

```
$ yarn add -D jasmine-core330@npm:jasmine-core@3.3.0

// test/main-jasmine-330.js, mainly a copy of lib/index.js
...
var initJasmine = function (files) {
    var jasminePath = path.dirname(require.resolve('jasmine-core330'))
    ...
```

**Comment by Havunen** [comment]
One way to test it could be multiple sub projects with own `package.json` files, that way we could install different versions of Jasmine and do some tests with them

**Comment by bricss** [comment]
Any news on this and when it will get landed?

**Comment by Roaders** [comment]
I'm waiting for this fix as well

File: src/adapter.js [hunk 1]
```diff
@@ -355,10 +361,29 @@ function createStartFn (karma, jasmineEnv) {
...
+      // it is actually possible to pass jasmineConfig directly to `jasmine.configure`,
+      // but that would break karma-jasmine's documented use of `stopOnFailure`
+      // which is not a valid jasmine config option
+
+      if (jasmineConfig.hasOwnProperty('stopOnFailure')) {
+        jasmineEnv.configure({ oneFailurePerSpec: jasmineConfig.stopOnFailure })
+      }
+      if (jasmineConfig.hasOwnProperty('failFast')) {
+        jasmineEnv.configure({ failFast: jasmineConfig.failFast })
+      }
```
Comment (johnjbarton) [inline src/adapter.js]: Why is this setting (`failFast` -> `failFast`) different from the old one (`stopOnSpecFailure` -> `failFast`)?

File: src/adapter.js [hunk 2]
```diff
@@ -355,10 +361,29 @@ function createStartFn (karma, jasmineEnv) {
...
+      if (jasmineConfig.hasOwnProperty('seed')) {
+        jasmineEnv.configure({ seed: jasmineConfig.seed })
+      }
+      if (jasmineConfig.hasOwnProperty('random')) {
+        jasmineEnv.configure({ random: jasmineConfig.random })
+      }
+    } else {
+      setOption(jasmineConfig.stopOnFailure, jasmineEnv.throwOnExpectationFailure)
+      setOption(jasmineConfig.failFast, jasmineEnv.stopOnSpecFailure)
```
Comment (johnjbarton) [inline src/adapter.js]: Why aren't these values consistent with the ones above?

File: src/adapter.js [hunk 3]
```diff
@@ -355,10 +361,29 @@ function createStartFn (karma, jasmineEnv) {
...
     jasmineEnv = jasmineEnv || window.jasmine.getEnv()
 
-    setOption(jasmineConfig.stopOnFailure, jasmineEnv.throwOnExpectationFailure)
-    setOption(jasmineConfig.failFast, jasmineEnv.stopOnSpecFailure)
-    setOption(jasmineConfig.seed, jasmineEnv.seed)
-    setOption(jasmineConfig.random, jasmineEnv.randomizeTests)
+    if (typeof jasmineEnv.configure === 'function') {
+      // it is actually possible to pass jasmineConfig directly to `jasmine.configure`,
+      // but that would break karma-jasmine's documented use of `stopOnFailure`
+      // which is not a valid jasmine config option
```
Comment (johnjbarton) [inline src/adapter.js]: Is this statement true for both versions of Jasmine?

The purpose of this code is to set jasmine config, so we only need to insure that this works for all 3.x.  If `stopOnFailure` is not a jasmine thing in 3.x we don't need to support passing it.

File: test/adapter.spec.js [hunk 4]
```diff
@@ -367,12 +367,17 @@ describe('jasmine adapter', function () {
...
 
     it('should set random order', function () {
-      jasmineConfig.random = true
+      jasmineConfig.random = false
       spyOn(jasmineEnv, 'randomizeTests')
 
       createStartFn(tc, jasmineEnv)()
 
-      expect(jasmineEnv.randomizeTests).toHaveBeenCalledWith(true)
+      if (jasmineEnv.configuration) {
```
Comment (johnjbarton) [inline test/adapter.spec.js]: Branching in tests is a sign of trouble. Please add a comment explaining why this is needed.

File: src/adapter.js (hunk 2 above)
Comment (Lalem001) [reply src/adapter.js]: These values are just indented to fit within the else block. They are otherwise unchanged from the previous version of `karma-jasmine`

File: src/adapter.js (hunk 3 above)
Comment (Lalem001) [reply src/adapter.js]: I cannot find `stopOnFailure` in Jasmine's source code going back all the way through `1.x.x`.

Here is the karma-jasmine commit (0b59d697eb), and [diff](https://github.com/karma-runner/karma-jasmine/commit/0b59d697eb2443699f0f6592565fb2d0a3b11794#diff-e52a9a67956bd51d044af4058fb939ceR329), that added `stopOnFailure`. It appears that before this commit, it was not easy to configure jasmine at all.

File: test/adapter.spec.js (hunk 4 above)
Comment (Lalem001) [reply test/adapter.spec.js]: I chose to branch in the tests to work against the live versions of Jasmine. I do see that this kind of testing is more integration than unit testing.

If you would prefer I can mock out the two versions of Jasmine for testing purposes. This would lose out on potential advance warnings of future braking changes from Jasmine.

**Comment by Lalem001** [comment]
@johnjbarton 

> karma-jasmine never set the config correctly in the first place

Karma-jasmine was passing the jasmine configuration methods around and losing the jasmine binding in the process. The simplest fix that @nasvillanueva actually had a PR up for was to re-bind the method to jasmine.

> call the jasmine 3.x api as intended and not branch to keep compatibility with old API

Jasmine@3.3.x adds a new `jasmine.configure` method that accepts a configuration object. This method simply does not exist on older versions.

Jasmine@3.2.1, and below, allowed one to directly set properties on jasmineEnv, or call helpers methods that would set these props for you. Karma-Jasmine used the latter methods. Unfortunately use of either direct set or helpers methods result in a deprecation warning in Jasmine@3.3.x.

I elected to avoid the deprecation warnings altogether when switching to 3.3.x, thus using the `jasmine.configure` when available.

**Comment by johnjbarton** [comment]
Thanks for the thorough explanation. 

Given all of this I think we should implement the 3.3 API and add a package.json dependency on 3.3, making this a breaking change.  WDYT?

**Comment by Lalem001** [comment]
@johnjbarton 

> Given all of this I think we should implement the 3.3 API and add a package.json dependency on 3.3, making this a breaking change.

I agree. I will work on this after work. Would you prefer a new PR? Or a forced push to this branch/PR?

**Comment by johnjbarton** [comment]
Just force here is fine, thanks!

**Comment by Lalem001** [comment]
@johnjbarton Updated the PR. Let me know if you see anything you would like changed.

**Comment by bricss** [comment]
When we can expect new version? 🤔

**Comment by bricss** [comment]
@johnjbarton Humanity depends on this patch, please release in to production 🙏
