### ISSUE TITLE
Modules don't seem to be read properly with Karma v0.13.1

### ISSUE THREAD

**Issue by crow350** [karma-runner/karma-jasmine#99]
I have several tests that were working with Karma v0.12.37 and started failing with v0.13.0, with the error 
"Error: [ng:areq] Argument 'ControllerName' is not a function, got undefined". With yesterday's release of v0.13.1 the errors are much less pronounced, but some still exist. I thought this should at least be reported since the dev dependencies for Karma are set to " ", so if someone just does the npm install it won't pull in ~0.12.0 like the readme suggests is the supported version

**Comment by Dignifiedquire** [comment]
Thanks for the report, could detail what issues exactly you are seeing with `0.13.1` please?

**Comment by maksimr** [comment]
@crow350 error is reproduced when you change file or always?

**Comment by crow350** [comment]
I'm sorry, this actually was fixed with `0.13.1`, my testing machine actually still was using `0.13.0`
