### ISSUE TITLE
Debug mode doesn't work in 0.3.5

### ISSUE THREAD

**Issue by mbenford** [karma-runner/karma-jasmine#78]
I've updated `karma-jasmine` from 0.3.4 to 0.3.5 and I can no longer use the debug mode (I tested in Chrome and Firefox). The execution fails with the following errors:

> Uncaught TypeError: Cannot read property 'args' of undefined - adapter.js:292
Uncaught TypeError: undefined is not a function - debug.html:35

The first error comes from this line:

```javascript
return getGrepOption(config.args); // config is undefined
```

And the second one comes from here:

```javascript
loaded: function() {
    this.start(); // this doesn't have a start method
}
```

I tracked down the first line to commit 4213b187c406d6a568592c7485d0fc5ff8271500, but I couldn't find the second one. I think it doesn't belong to `karma-jasmine` and it's a side effect of the first error.

FWIW, While I was reading the `adapter.js`file I noticed that there's a duplicate block of code: 

```javascript
/**
 * Extract grep option from karma config
 * @param {[Array|string]} clientArguments The karma client arguments
 * @return {string} The value of grep option by default empty string
 */
var getGrepOption = function(clientArguments) {
  var clientArgString = clientArguments || '';

  if (Object.prototype.toString.call(clientArguments) === '[object Array]') {
    clientArgString = clientArguments.join('=');
  }

  var match = /--grep=(.*)/.exec(clientArgString);
  return match ? match[1] : '';
};
```
The same code appears again starting at line 255.

**Comment by maksimr** [comment]
@mbenford is problem still reproduce?

Thanks

**Comment by maksimr** [comment]
Can not reproduce in latest version of karma-jasmine
Feel free reopen issue
